# Generated by Django 4.1.7 on 2023-04-06 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('receipt_type', models.CharField(choices=[('client', 'Client'), ('kitchen', 'Kitchen')], max_length=7)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('client', 'Client'), ('kitchen', 'Kitchen')], max_length=7)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='new', max_length=11)),
                ('pdf_file', models.FileField(upload_to='')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt.printer')),
            ],
        ),
    ]
