# Generated by Django 4.1.7 on 2023-04-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_alter_receipt_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='./media/pdf'),
        ),
    ]
